name:                tscleaner
version:             0.1.0.0
github:              "githubuser/tscleaner"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tscleaner#readme>

dependencies:
- base >= 4.7 && < 5
- monad-logger
- text
- time

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Werror=incomplete-patterns
  - -Werror=incomplete-uni-patterns
  - -Wredundant-constraints
  - -Werror=missing-fields
  - -Wmissing-methods

default-extensions:
  - NumericUnderscores
  - OverloadedStrings
  - TypeApplications

library:
  source-dirs: src
  dependencies:
    - mtl

executables:
  tscleaner-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tscleaner
    - optparse-applicative

tests:
  tscleaner-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tscleaner
    - QuickCheck
    - containers
    - hspec
    - hspec-discover
    - monad-loops
    - mtl
