name:                gfs
version:             0.2.1
github:              "eunikolsky/gfs"
license:             BSD3
author:              "Eugene Nikolsky"
maintainer:          "e@egeek.me"
copyright:           "2023 Eugene Nikolsky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/eunikolsky/gfs#readme>

dependencies:
- base >= 4.7 && < 5
- monad-logger
- text
- time

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Werror=incomplete-patterns
  - -Werror=incomplete-uni-patterns
  - -Wredundant-constraints
  - -Werror=missing-fields
  - -Wmissing-methods

default-extensions:
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - NamedFieldPuns
  - NumericUnderscores
  - OverloadedStrings
  - TypeApplications

library:
  source-dirs: src
  dependencies:
    - mtl

executables:
  gfs:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gfs
    - mtl
    - optparse-applicative

tests:
  gfs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gfs
    - QuickCheck
    - containers
    - hspec
    - hspec-discover
    - monad-loops
    - mtl
    - quickcheck-instances
